import 'package:blanch_menu_app/model/post_model.dart';

class DemoValues {
  static final List<PostModel> posts = [
    PostModel(
      id: "1",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Allergen Free Pancakes",
    ),
    PostModel(
      id: "2",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Miso Soup",
    ),
    PostModel(
      id: "3",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Rice Congee",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Global",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Wok",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Halal",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Harvest",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "4",
      meal: "Breakfast",
      station: "Kosher",
      menu_item: "Steel-cut Oatmeal",
    ),
    PostModel(
      id: "5",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Blueberries",
    ),
    PostModel(
      id: "6",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Brown Sugar",
    ),
    PostModel(
      id: "7",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Craisins",
    ),
    PostModel(
      id: "8",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Diced Mangos",
    ),
    PostModel(
      id: "9",
      meal: "Breakfast",
      station: "Classics",
      menu_item: "Golden Raisins",
    ),
    PostModel(
      id: "10",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Brined Chicken Breast",
    ),
    PostModel(
      id: "11",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Pork Tacos",
    ),
    PostModel(
      id: "12",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Portuguese Sausage and Potato Soup",
    ),
    PostModel(
      id: "13",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Baked Sweet Potatoes",
    ),
    PostModel(
      id: "14",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Black beans and White rice",
    ),
    PostModel(
      id: "15",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Whole Kernel Corn",
    ),
    PostModel(
      id: "16",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Cilantro",
    ),
    PostModel(
      id: "17",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Corn Tortillas",
    ),
    PostModel(
      id: "18",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Salsa Verde",
    ),
    PostModel(
      id: "19",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Sour Cream",
    ),
    PostModel(
      id: "20",
      meal: "Lunch",
      station: "Classics",
      menu_item: "Taco Shells",
    ),
    PostModel(
      id: "21",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Grilled Pork with Glazed Apples",
    ),
    PostModel(
      id: "22",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Herbed Tofu & Veggie Sauté",
    ),
    PostModel(
      id: "23",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Local Roasted Breast of Turkey",
    ),
    PostModel(
      id: "24",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Portuguese Sausage and Potato Soup",
    ),
    PostModel(
      id: "25",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Baked Sweet Potato",
    ),
    PostModel(
      id: "26",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Butter-squash",
    ),
    PostModel(
      id: "27",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Cornbread stuffing",
    ),
    PostModel(
      id: "28",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Mashed Potatoes",
    ),
    PostModel(
      id: "29",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Whole Grain Brown Rice",
    ),
    PostModel(
      id: "30",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Cranberry Sauce",
    ),
    PostModel(
      id: "31",
      meal: "Dinner",
      station: "Classics",
      menu_item: "Gluten Free Turkey Gravy",
    ),
    PostModel(
      id: "32",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Hard Cooked Eggs",
    ),
    PostModel(
      id: "33",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Scrambled Eggs",
    ),
    PostModel(
      id: "34",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Vegetarian Mount Holyokes",
    ),
    PostModel(
      id: "35",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Chicken Sausage",
    ),
    PostModel(
      id: "36",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Hashbrowns",
    ),
    PostModel(
      id: "37",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Minced Jalapeno Peppers",
    ),
    PostModel(
      id: "38",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Pico de Gallo w/ Salsa",
    ),
    PostModel(
      id: "39",
      meal: "Breakfast",
      station: "Grill",
      menu_item: "Strawberries",
    ),
    PostModel(
      id: "40",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Roast Beef Sandwich",
    ),
    PostModel(
      id: "41",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Miso Chicken Wings",
    ),
    PostModel(
      id: "42",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Sweet Garlic Tofu",
    ),
    PostModel(
      id: "43",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Fresh Veggie of the day",
    ),
    PostModel(
      id: "44",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Spring Asparagus Sauce",
    ),
    PostModel(
      id: "45",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Sweet Potato French Fries",
    ),
    PostModel(
      id: "46",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Pita Bread",
    ),
    PostModel(
      id: "47",
      meal: "Lunch",
      station: "Grill",
      menu_item: "Hummus",
    ),
    PostModel(
      id: "48",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Local Beef Hamburger Patty",
    ),
    PostModel(
      id: "49",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Local Hamburger on a Roll",
    ),
    PostModel(
      id: "50",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Oven Roasted Carrots",
    ),
    PostModel(
      id: "51",
      meal: "Dinner",
      station: "Grill",
      menu_item: "White Rice",
    ),
    PostModel(
      id: "52",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Corn Tortilla",
    ),
    PostModel(
      id: "53",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Grill Pickle Chips",
    ),
    PostModel(
      id: "54",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Flour-tortillas",
    ),
    PostModel(
      id: "55",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Fresh Lime Wedges",
    ),
    PostModel(
      id: "56",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Sour Cream",
    ),
    PostModel(
      id: "57",
      meal: "Dinner",
      station: "Grill",
      menu_item: "Lettuce chips",
    ),
    PostModel(
      id: "58",
      meal: "Lunch",
      station: "Global",
      menu_item: "Fresh vegetable of the day",
    ),
    PostModel(
      id: "59",
      meal: "Lunch",
      station: "Global",
      menu_item: "Garlic bread",
    ),
    PostModel(
      id: "60",
      meal: "Lunch",
      station: "Global",
      menu_item: "Gnocci w/Cheese and Pancetta",
    ),
    PostModel(
      id: "61",
      meal: "Lunch",
      station: "Global",
      menu_item: "Philly Cheese Stake Calzone",
    ),
    PostModel(
      id: "62",
      meal: "Dinner",
      station: "Global",
      menu_item: "Classic Cheese Pizza",
    ),
    PostModel(
      id: "63",
      meal: "Dinner",
      station: "Global",
      menu_item: "Thin Spaghetti",
    ),
    PostModel(
      id: "64",
      meal: "Dinner",
      station: "Global",
      menu_item: "Tofu Ravioli Pomodoro",
    ),
    PostModel(
      id: "65",
      meal: "Lunch",
      station: "Wok",
      menu_item: "Beef and Bok Choy",
    ),
    PostModel(
      id: "66",
      meal: "Lunch",
      station: "Wok",
      menu_item: "Stir Fried Thai Tofu w/ Noodles",
    ),
    PostModel(
      id: "67",
      meal: "Lunch",
      station: "Wok",
      menu_item: "Homemade Chicken Broth",
    ),
    PostModel(
      id: "68",
      meal: "Lunch",
      station: "Wok",
      menu_item: "Vegetable Potstickers",
    ),
    PostModel(
      id: "69",
      meal: "Lunch",
      station: "Wok",
      menu_item: "White Rice",
    ),
    PostModel(
      id: "70",
      meal: "Dinner",
      station: "Wok",
      menu_item: "Beef and Bok Choy",
    ),
    PostModel(
      id: "71",
      meal: "Dinner",
      station: "Wok",
      menu_item: "Stir Fried Thai Tofu w/ Noodles",
    ),
    PostModel(
      id: "72",
      meal: "Dinner",
      station: "Wok",
      menu_item: "Homemade Chicken Broth",
    ),
    PostModel(
      id: "73",
      meal: "Dinner",
      station: "Wok",
      menu_item: "Vegetable Potstickers",
    ),
    PostModel(
      id: "74",
      meal: "Dinner",
      station: "Wok",
      menu_item: "White Rice",
    ),
    PostModel(
      id: "75",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Chicken Shawarma",
    ),
    PostModel(
      id: "76",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Indian Dal",
    ),
    PostModel(
      id: "77",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Sautéed Mushrooms",
    ),
    PostModel(
      id: "78",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Tomatoes w/ Basil",
    ),
    PostModel(
      id: "79",
      meal: "Lunch",
      station: "Halal",
      menu_item: "White Rice",
    ),
    PostModel(
      id: "80",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Cucumber Yogurt Rita with Tomato",
    ),
    PostModel(
      id: "81",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Diced Cucumbers",
    ),
    PostModel(
      id: "82",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Diced Tomatoes",
    ),
    PostModel(
      id: "83",
      meal: "Lunch",
      station: "Halal",
      menu_item: "Naan Bread",
    ),
    PostModel(
      id: "84",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Lamb Jalfrezi",
    ),
    PostModel(
      id: "85",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Indian Dall",
    ),
    PostModel(
      id: "86",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Vegan Chicken Jalfrezi",
    ),
    PostModel(
      id: "87",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Basmati Rice",
    ),
    PostModel(
      id: "88",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Broccoli Florets",
    ),
    PostModel(
      id: "89",
      meal: "Dinner",
      station: "Halal",
      menu_item: "Naan Bread",
    ),
    PostModel(
      id: "90",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Beef Stew",
    ),
    PostModel(
      id: "91",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Breaded Chicken Cutlets",
    ),
    PostModel(
      id: "92",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Chicken Rice Soup",
    ),
    PostModel(
      id: "93",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Fresh Veggie of the Day",
    ),
    PostModel(
      id: "94",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Steamed Carrots",
    ),
    PostModel(
      id: "95",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Corn Chips",
    ),
    PostModel(
      id: "96",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Green Leaf Lettuce Cups",
    ),
    PostModel(
      id: "97",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Hamburger Rolls",
    ),
    PostModel(
      id: "98",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Spicy Spiral Fries",
    ),
    PostModel(
      id: "99",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Whole Grain Brown Rice",
    ),
    PostModel(
      id: "100",
      meal: "Lunch",
      station: "Kosher",
      menu_item: "Oatmeal Cookies",
    ),
    PostModel(
      id: "101",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Grilled Marinated Chicken",
    ),
    PostModel(
      id: "102",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Saffron Rice",
    ),
    PostModel(
      id: "103",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Vegan Lemon Dal",
    ),
    PostModel(
      id: "104",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Chicken Rice Soup",
    ),
    PostModel(
      id: "105",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Sautéed Spinach with Garlic",
    ),
    PostModel(
      id: "106",
      meal: "Dinner",
      station: "Kosher",
      menu_item: "Oven Roasted Sweet Potatoes",
    ),
    PostModel(
      id: "107",
      meal: "Breakfast",
      station: "Harvest",
      menu_item: "Chocolate Chip Bread",
    ),
    PostModel(
      id: "108",
      meal: "Breakfast",
      station: "Harvest",
      menu_item: "Cinnamon Cheese Braid",
    ),
    PostModel(
      id: "109",
      meal: "Lunch",
      station: "Harvest",
      menu_item: "Chocolate Brownies",
    ),
    PostModel(
      id: "110",
      meal: "Lunch",
      station: "Harvest",
      menu_item: "Nutella Hazelnut Blondie Brownies",
    ),
    PostModel(
      id: "111",
      meal: "Lunch",
      station: "Harvest",
      menu_item: "White Chocolate Raspberry Butter Cookies",
    ),
    PostModel(
      id: "112",
      meal: "Dinner",
      station: "Harvest",
      menu_item: "CHeesecake",
    ),
    PostModel(
      id: "113",
      meal: "Dinner",
      station: "Harvest",
      menu_item: "Twix Caramel Cake",
    ),
  ];
}
